const { KEYWORDS } = require("../../gameSettings");

const dwgUpdated = [
    {
        name: 'Marauder',
        isBuiltIn: true,
        cardText: 'When this vehicle is played, draw a vehicle card from the enemy deck',
        materialCost: 55000,
        blueprintCost: 40205,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.DWG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Plunderer',
        isBuiltIn: true,
        cardText: 'Costs 20k less for each friendly vehicle in play. When this vehicle survives a victorious fleet battle or inflicts damage to the enemy base, draw one card from the enemy deck, but increase its cost by 20k',
        materialCost: 180000,
        blueprintCost: 187000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.DWG,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.SCRAPPY],
    },
    {
        name: 'Tarpon',
        isBuiltIn: true,
        cardText: 'While this vehicle is alive, you may not play any other aircraft into this zone',
        materialCost: 510000,
        blueprintCost: 511605,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.DWG,
        blueprintId: null,
        keywords: [KEYWORDS.FRAGILE, KEYWORDS.SUB_SCREEN],
    },
    {
        name: 'Loggerhead',
        isBuiltIn: true,
        cardText: 'When this vehicle is destroyed, shuffle another copt of it into your deck. It costs 0.',
        materialCost: 70000,
        blueprintCost: 74000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.DWG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Buccaneer',
        isBuiltIn: true,
        cardText: '',
        materialCost: 225000,
        blueprintCost: 296000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.DWG,
        blueprintId: null,
        keywords: [KEYWORDS.FRAGILE],
    },
    {
        name: 'Spawn Buccaneer',
        isBuiltIn: true,
        cardText: 'Spawn a Buccaneer into a zone. It is not temporary. It gains the Scrappy keyword.',
        materialCost: 225000,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.DWG,
        blueprintId: null,
    },
];

const owNew = [
    {
        name: 'Brandistock',
        isBuiltIn: true,
        cardText: 'When this card is destroyed, draw a random GT Airship',
        materialCost: 250000,
        blueprintCost: 258000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [KEYWORDS.SUB_SCREEN],
    },
];

const owUpdated = [
    {
        name: 'Bulwark',
        isBuiltIn: true,
        cardText: '',
        materialCost: 450000,
        blueprintCost: 848000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'The Onyx Throne',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle would partake in a defensive battle, spawn an allied parapet to fight alongside it. Once per turn, you may pay 1cp to draw a GT heavy airship card.',
        materialCost: 500000,
        blueprintCost: 492482,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.INOFFENSIVE],
    },
    {
        name: 'Eyrie',
        isBuiltIn: true,
        cardText: '',
        materialCost: 575000,
        blueprintCost: 809000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.FRAGILE],
    },
    {
        name: 'Rook',
        isBuiltIn: true,
        cardText: 'Draw a card when played',
        materialCost: 50000,
        blueprintCost: 98841,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [],
    },
];

const owDeleted = [
    {
        name: 'Halberd',
        isBuiltIn: true,
        cardText: 'When this card is destroyed, draw a random GT Airship',
        materialCost: 120000,
        blueprintCost: 121363,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'vehicle',
        faction: FACTIONS.OW,
        blueprintId: null,
        keywords: [KEYWORDS.SUB_SCREEN],
    },
];

const ssNew = [
    {
        name: 'Thresher Shark',
        isBuiltIn: true,
        cardText: 'While you have less resources than this costs, you may play it with HALFCOST and INOFFENSIVE',
        materialCost: 580000,
        blueprintCost: 914000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.SUB_SCREEN],
    },
    {
        name: 'Bull Shark',
        isBuiltIn: true,
        cardText: 'Whenever this survives an offensive fleet battle, deal 200k damage to enemy base in this zone',
        materialCost: 640000,
        blueprintCost: 898000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.SUB_SCREEN],
    },
    {
        name: 'Tiger Shark',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle is played into a zone, reduce the maximum number of vehicle slots for your opponent in this zone by 3',
        materialCost: 690000,
        blueprintCost: 914000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Cash advance',
        isBuiltIn: true,
        cardText: 'Gain 150k resources this turn, then draw a card.',
        materialCost: 0,
        blueprintCost: 0,
        cpCost: 2,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.SS,
        blueprintId: null,
    },
];

const ssUpdated = [
    {
        name: 'Iron Maiden',
        isBuiltIn: true,
        cardText: 'When this vehicle is destroyed, draw a card',
        materialCost: 150000,
        blueprintCost: 174000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Victoria',
        isBuiltIn: true,
        cardText: 'When played, pick one SS ship in hand and reduce its cost by 75k',
        materialCost: 250000,
        blueprintCost: 270185,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Trondheim',
        isBuiltIn: true,
        cardText: 'When this vehicle is destroyed, draw an SS ship and reduce its cost by 75k',
        materialCost: 375000,
        blueprintCost: 393000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Air Strafe',
        isBuiltIn: true,
        cardText: 'Choose an enemy vehicle, it fights alone against two predatorX. If the target is a player design, also spawn your choice of hydra or cyclone',
        materialCost: 150000,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.SS,
        blueprintId: null,
    },
    {
        name: 'Repairmen Ready',
        isBuiltIn: true,
        cardText: 'Grant target vehicle scrappy. If the target is an SS vehicle that costs less than 400k, draw a card.',
        materialCost: 0,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.SS,
        blueprintId: null,
    },
    {
        name: 'Excalibur',
        isBuiltIn: true,
        cardText: 'Pick one SS ship in hand and reduce its cost by 200k',
        materialCost: 550000,
        blueprintCost: 553900,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Asphodel',
        isBuiltIn: true,
        cardText: '',
        materialCost: 400000,
        blueprintCost: 544000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.AIR_SCREEN, KEYWORDS.STEALTHY],
    },
    {
        name: 'Braveheart',
        isBuiltIn: true,
        cardText: 'Once per turn, you may pay 1cp to have any friendly ship in this zone 1v1 an enemy vehicle in the same zone',
        materialCost: 350000,
        blueprintCost: 371000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Tyr',
        isBuiltIn: true,
        cardText: 'This card costs 60k less for every turn it spends in your hand',
        materialCost: 950000,
        blueprintCost: 983000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Nothung',
        isBuiltIn: true,
        cardText: 'When played, reduce the cost of all SS ships in your hand by 40k',
        materialCost: 400000,
        blueprintCost: 478000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Sacrilego',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle participates in a fleet battle, friendly ships receive SCRAPPY keyword for that battle. Whenever this vehicle survives a fleet battle, reduce the cost of SS ships in hand by 30k.',
        materialCost: 10000,
        blueprintCost: 86000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.SCRAPPY, KEYWORDS.STEALTHY, KEYWORDS.MOBILE],
    },
    {
        name: 'Resolute',
        isBuiltIn: true,
        cardText: 'When this vehicle is played, draw an SS ship from your deck. reduce its cost by 40k',
        materialCost: 60000,
        blueprintCost: 63300,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Typhoon',
        isBuiltIn: true,
        cardText: 'When played into a zone, summon a second copy of it in that zone',
        materialCost: 130000,
        blueprintCost: 135323,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Cyclone',
        isBuiltIn: true,
        cardText: 'When played into a zone, give all enemy vehicles in that zone the fragile keyword',
        materialCost: 280000,
        blueprintCost: 281000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Wolin',
        isBuiltIn: true,
        cardText: '',
        materialCost: 250000,
        blueprintCost: 271000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Spectre',
        isBuiltIn: true,
        cardText: 'When played, reduce your opponents cp by 1 (min 0)',
        materialCost: 200000,
        blueprintCost: 214000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY],
    },
    {
        name: 'Mobula',
        isBuiltIn: true,
        cardText: '',
        materialCost: 500000,
        blueprintCost: 603000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.PLANE,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.HALF_COST, KEYWORDS.TEMPORARY],
    },
    {
        name: 'Hydra',
        isBuiltIn: true,
        cardText: 'When played, refresh one of your hero powers then gain 1cp',
        materialCost: 220000,
        blueprintCost: 238000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.MOBILE],
    },
    {
        name: 'Chrysaor',
        isBuiltIn: true,
        cardText: 'While you have more than 150k resources, this card costs 75k more and spawns in a second Chrysaor',
        materialCost: 75000,
        blueprintCost: 116000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY],
    },
    {
        name: 'Argonaut',
        isBuiltIn: true,
        cardText: 'When this is destroyed, reduce the cost of a random SS ship in your hand by 50k',
        materialCost: 90000,
        blueprintCost: 94000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.SCRAPPY],
    },
    {
        name: 'Paladin',
        isBuiltIn: true,
        cardText: 'When played, gain 1 cp. Once per turn, you may pay 1cp to spawn another Paladin',
        materialCost: 240000,
        blueprintCost: 240000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Balmung',
        isBuiltIn: true,
        cardText: 'When this is played into a zone, create a hydra card in hand and reduce its cost to zero',
        materialCost: 620000,
        blueprintCost: 636000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
];

const ssDeleted = [
    {
        name: 'Dryad',
        isBuiltIn: true,
        cardText: 'Whenever this ship participates in a defensive battle, spawn another dryad into the zone under your control',
        materialCost: 40500,
        blueprintCost: 40500,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.SS,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
];

const tgNew = [
    {
        name: 'Mania',
        isBuiltIn: true,
        cardText: '',
        materialCost: 270000,
        blueprintCost: 574000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.ROBOTIC, KEYWORDS.UPKEEP_REQUIRED],
    },
    {
        name: 'Spawn Audacious',
        isBuiltIn: true,
        cardText: 'Spawn an audacious into target zone. It is not temporary.',
        materialCost: 40000,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.TG,
        blueprintId: null,
    },
    {
        name: 'Agony',
        isBuiltIn: true,
        cardText: 'When played, grant an enemy vehicle FRAGILE',
        materialCost: 375000,
        blueprintCost: 440000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Wonder',
        isBuiltIn: true,
        cardText: 'When played, refresh all your hero powers and gain 1cp',
        materialCost: 700000,
        blueprintCost: 865000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Repurpose',
        isBuiltIn: true,
        cardText: 'Target a friendly TG vehicle. destroy it. gain resources this turn equal to its cost.',
        materialCost: 0,
        blueprintCost: 0,
        cpCost: 1,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.TG,
        blueprintId: null,
    },
];

const tgUpdated = [
    {
        name: 'Jealousy',
        isBuiltIn: true,
        cardText: 'When this vehicle is destroyed, draw a card',
        materialCost: 375000,
        blueprintCost: 406000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER],
    },
    {
        name: 'Obsession',
        isBuiltIn: true,
        cardText: '',
        materialCost: 300000,
        blueprintCost: 337000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.UPKEEP_REQUIRED, KEYWORDS.ROBOTIC],
    },
    {
        name: 'Euphoria',
        isBuiltIn: true,
        cardText: '',
        materialCost: 300000,
        blueprintCost: 581000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.UPKEEP_REQUIRED, KEYWORDS.ROBOTIC],
    },
    {
        name: 'Horror',
        isBuiltIn: true,
        cardText: 'Whenever a horror participates in an offensive fleet battle, create anther copy of it in this zone. Max one spawn per zone',
        materialCost: 50000,
        blueprintCost: 77000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.ROBOTIC],
    },
    {
        name: 'Nostalgia',
        isBuiltIn: true,
        cardText: 'Whenever this would be destroyed, put it back into your hand.',
        materialCost: 75000,
        blueprintCost: 98000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.ROBOTIC],
    },
    {
        name: 'Alarmed',
        isBuiltIn: true,
        cardText: 'Can only play this into a zone in which you control a AI vehicle. When this vehicle is played, sacrifice a target friendly AI vehicle in this zone',
        materialCost: 0,
        blueprintCost: 250000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.ROBOTIC],
    },
    {
        name: 'Anguish',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle fights in a fleet battle, it must deploy first before the opponent',
        materialCost: 200000,
        blueprintCost: 202000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.UPKEEP_REQUIRED, KEYWORDS.ROBOTIC],
    },
    {
        name: 'Curiosity',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle is played into a zone, spawn a second curiosity into that zone too',
        materialCost: 40000,
        blueprintCost: 46000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Duel',
        isBuiltIn: true,
        cardText: 'Target a friendly and enemy vehicle. They can be in different zones. they 1v1. If the opponents vehicle dies, draw a card.',
        materialCost: 0,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.TG,
        blueprintId: null,
    },
    {
        name: 'Fear',
        isBuiltIn: true,
        cardText: 'When this vehicle is played, spawn a friendly horror into each zone',
        materialCost: 500000,
        blueprintCost: 800000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.ROBOTIC, KEYWORDS.UPKEEP_REQUIRED],
    },
    {
        name: 'Spite',
        isBuiltIn: true,
        cardText: 'When played, grant an enemy vehicle FRAGILE',
        materialCost: 120000,
        blueprintCost: 128000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Vengeful',
        isBuiltIn: true,
        cardText: 'Whenever you lose a vehicle to a fleet battle (any zone) this unit deals 40k damage to the enemy base in this zone',
        materialCost: 150000,
        blueprintCost: 168000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Havoc Factory',
        isBuiltIn: true,
        cardText: 'Target friendly robotic vehicle. Whenever that vehicle is engaged in a fleet combat, spawn a Havoc swarm to fight along side it',
        materialCost: 25000,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.TG,
        blueprintId: null,
    },
    {
        name: 'Mirth Factory',
        isBuiltIn: true,
        cardText: 'Target friendly robotic vehicle. Whenever that vehicle is engaged in a fleet combat, spawn a Mirth swarm to fight along side it',
        materialCost: 60000,
        blueprintCost: 0,
        cpCost: 0,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.TG,
        blueprintId: null,
    },
    {
        name: 'Obelisk',
        isBuiltIn: true,
        cardText: 'Whenever this vehicle participates in a fleet battle, spawn a temporary Mirth swarm to fight on your side in the battlefield',
        materialCost: 40000,
        blueprintCost: 32000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY],
    },
    {
        name: 'Loathing',
        isBuiltIn: true,
        cardText: 'When played, target enemy vehicle in this zone, it gains inoffensive',
        materialCost: 225000,
        blueprintCost: 268000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [],
    },
];

const tgDeleted = [
    {
        name: 'Amusement',
        isBuiltIn: true,
        cardText: '',
        materialCost: 330000,
        blueprintCost: 334000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.AIRSHIP,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.UPKEEP_REQUIRED, KEYWORDS.ROBOTIC],
    },
    {
        name: 'Acceptance',
        isBuiltIn: true,
        cardText: 'If you have at least 150k materials, this card loses halfcost keyword and spawns a second acceptance',
        materialCost: 150000,
        blueprintCost: 159000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.PLANE,
        type: 'vehicle',
        faction: FACTIONS.TG,
        blueprintId: null,
        keywords: [KEYWORDS.HALF_COST, KEYWORDS.TEMPORARY],
    },
];

const wfNew = [
    {
        name: 'Sub Strike',
        isBuiltIn: true,
        cardText: 'Target an enemy submarine, remove it from play.',
        materialCost: 100000,
        blueprintCost: 0,
        cpCost: 1,
        playerId: null,
        vehicleType: null,
        type: 'ability',
        faction: FACTIONS.WF,
        blueprintId: null,
    },
];

const wfUpdated = [
    {
        name: 'Buzzsaw',
        isBuiltIn: true,
        cardText: 'When played, put an ambush card into your hand',
        materialCost: 75000,
        blueprintCost: 88000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY, KEYWORDS.SCRAPPY],
    },
    {
        name: 'Veles',
        isBuiltIn: true,
        cardText: 'This card may be spawned into battle after all enemies are already spawned in',
        materialCost: 225000,
        blueprintCost: 286922,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY, KEYWORDS.SCRAPPY],
    },
    {
        name: 'Excruciator',
        isBuiltIn: true,
        cardText: 'When played, draw two AI vehicles from your deck and reduce their cost by 100k.',
        materialCost: 600000,
        blueprintCost: 663000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.BLOCKER, KEYWORDS.SUB_SCREEN],
    },
    {
        name: 'Scourge',
        isBuiltIn: true,
        cardText: 'When played, gain 1cp',
        materialCost: 225000,
        blueprintCost: 209000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.SCRAPPY],
    },
    {
        name: 'Pandemonium',
        isBuiltIn: true,
        cardText: '',
        materialCost: 225000,
        blueprintCost: 244000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY, KEYWORDS.SUB_SCREEN],
    },
    {
        name: 'Disemboweler',
        isBuiltIn: true,
        cardText: 'When played, gain 1 cp.',
        materialCost: 300000,
        blueprintCost: 305000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Pulverizer',
        isBuiltIn: true,
        cardText: 'Spawn two additional copies of this vehicle into the zone',
        materialCost: 78000,
        blueprintCost: 78000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Slasher',
        isBuiltIn: true,
        cardText: 'When this is played, add two earth rakers to your hand. they cost 0.',
        materialCost: 300000,
        blueprintCost: 353000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [],
    },
    {
        name: 'Earth Raker',
        isBuiltIn: true,
        cardText: 'When this is played, draw a card',
        materialCost: 50000,
        blueprintCost: 51000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.STEALTHY],
    },
    {
        name: 'Purifier',
        isBuiltIn: true,
        cardText: 'This vehicle does no damage to the enemy base. Whenever it participates in a fleet battle, the enemy forces must spawn in first, even if they are defending.',
        materialCost: 750000,
        blueprintCost: 765000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.HALF_COST, KEYWORDS.FRAGILE],
    },
    {
        name: 'Pontus',
        isBuiltIn: true,
        cardText: 'When this sub is played into a zone, spawn two additional copies into that same zone.',
        materialCost: 75000,
        blueprintCost: 56000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SUB,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.FRAGILE],
    },
    {
        name: 'Judgement',
        isBuiltIn: true,
        cardText: 'While your opponent has a submarine or airship, this card costs 100k less. Each turn, you may have this vehicle 1v1 an enemy submarine or airship in this zone.',
        materialCost: 540000,
        blueprintCost: 546000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [],
    },
];

const wfDeleted = [
    {
        name: 'Harbringer',
        isBuiltIn: true,
        cardText: 'Whenever this ship is in fleet combat, you may spawn in one WF ship that costs <=100k to join the battle',
        materialCost: 550000,
        blueprintCost: 551000,
        cpCost: 0,
        playerId: null,
        vehicleType: VEHICLE_TYPES.SHIP,
        type: 'vehicle',
        faction: FACTIONS.WF,
        blueprintId: null,
        keywords: [KEYWORDS.SUB_SCREEN],
    },
];

